---

- name: Run show commands on routers
  hosts: cisco_routers

  tasks:

    - name: run sh ip int br
      ios_command:
        commands: show ip int br
      register: sh_ip_int_br_result

    - name: Debug registered var
      debug:
        msg: "{{ sh_ip_int_br_result.stdout[0] | parse_cli_textfsm('templates/cisco_ios_show_ip_interface_brief.template') }}"

