---

- name: Run show commands on routers
  hosts: 191.168.100.1

  tasks:

    - name: run commands that require answering a prompt
      ios_command:
        commands:
          - command: 'clear counters Ethernet0/1'
            prompt: 'Clear "show interface" counters on this interface \[confirm\]'
            answer: 'y'
          - command: 'clear counters Ethernet0/2'
            prompt: '[confirm]'
            answer: "\r"
