---

- name: Collect IOS facts
  hosts: cisco_routers

  tasks:

    - name: Facts
      ios_facts:
        gather_subset: all

    - name: Create all_facts dir
      file:
        path: ./all_facts/
        state: directory
        mode: 0755

    - name: Copy facts to files
      copy:
        content: "{{ ansible_facts | to_nice_json }}"
        dest: "all_facts/{{inventory_hostname}}_facts.json"
